version: '3.9'

services:
  web:
    container_name: dj-web
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
